# Application
spring.application.name=contacts-service
server.port=8081

# Base de donnees
spring.datasource.url=jdbc:mariadb://contacts-db:3306/contacts_db
spring.datasource.username=contacts_user
spring.datasource.password=contacts_pass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Logs
logging.level.com.transfafrica=INFO
