spring.application.name=achats-service
server.port=8084
spring.datasource.url=jdbc:mariadb://achats-db:3306/achats_db
spring.datasource.username=achats_user
spring.datasource.password=achats_pass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
logging.level.com.transfafrica=INFO
